import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { SESSION_COOKIE, verifySessionToken, getSessionSecret } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get(SESSION_COOKIE)?.value;
  const isAuthed = token ? await verifySessionToken(token, getSessionSecret()) : false;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isAuthed && (
          <header className="flex items-center justify-end gap-3 px-4 py-2 border-b border-gray-200 dark:border-gray-800 text-sm text-gray-500 dark:text-gray-400">
            <span>Logged in</span>
            <span aria-hidden="true">·</span>
            <form action="/api/auth/logout" method="POST">
              <button
                type="submit"
                className="underline underline-offset-2 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
              >
                Logout
              </button>
            </form>
          </header>
        )}
        {children}
      </body>
    </html>
  );
}
